HEADER = 256
PORT = 5051
FORMAT = 'utf-8'
DISCONNECT_MESSAGE = "!DISCONNECT"
BUFFER_SIZE = 2048
CLIENT_FRAMESAVE = "client/frame.jpg"
SERVER_FRAMESAVE = 'server/framesaved.jpg'

TEXT_MSG = "T"
FRAME_MSG = "M"
IMG_MSG = "I"